name       : evolution-data-server
version    : 3.48.1
release    : 83
source     :
    - https://gitlab.gnome.org/GNOME/evolution-data-server/-/archive/3.48.1/evolution-data-server-3.48.1.tar.gz : b8d30a44555818d3f81a447c1c45b99dd6aa92ae60053b9e628583988c2c8bf6
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(gweather4)
    - pkgconfig(icu-uc)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.1)
    - pkgconfig(webkitgtk-6.0)
    - db5-devel
    - gperf
    - openldap-devel
    - vala
setup      : |
    %cmake \
        -DENABLE_INTROSPECTION=ON \
        -DENABLE_UOA=OFF \
        -DENABLE_VALA_BINDINGS=ON \
        -DSYSCONF_INSTALL_DIR="/usr/share" \
        -DWITH_KRB5=OFF \
        -DENABLE_GTK4=ON \
        -DENABLE_WEATHER=ON .
build      : |
    make -j1
install    : |
    %make_install

