name       : evolution-data-server
version    : 3.20.5
release    : 14
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/evolution-data-server/3.20/evolution-data-server-3.20.5.tar.xz : 0d1586cd326d997497a2a6fddd939a83892be07cb20f8c88fda5013f8c5bbe7e
license    : GPL-2.0
component  : desktop.gnome.core
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkitgtk-3.0)
    - gperf
    - vala
setup      : |
    %configure --disable-static --disable-uoa --enable-vala-bindings
build      : |
    %make
install    : |
    %make_install

