name       : evolution-data-server
version    : 3.42.0
release    : 69
source     :
    - https://download.gnome.org/sources/evolution-data-server/3.42/evolution-data-server-3.42.0.tar.xz : e8fdd3bc47a07d6f8a3052bbcae880f20f6dbc4f6973a8e90d00169bb99b1635
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - db5-devel
    - gperf
    - openldap-devel
    - vala
setup      : |
    %cmake \
        -DENABLE_INTROSPECTION=ON \
        -DENABLE_UOA=OFF \
        -DENABLE_VALA_BINDINGS=ON \
        -DSYSCONF_INSTALL_DIR="/usr/share" \
        -DWITH_KRB5=OFF .
build      : |
    make -j1
install    : |
    %make_install

