name       : evolution-data-server
version    : 3.18.4
release    : 11
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evolution-data-server/3.18/evolution-data-server-3.18.4.tar.xz : 0b756f05feae538676832acc122407046a89d4dd32da725789229dc3c416433f
license    : GPL-2.0
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(icu-uc)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(sqlite3)
    - pkgconfig(libgdata)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - gperf
    - vala
    - pkgconfig(gobject-introspection-1.0)
setup      : |
    %configure --disable-static --disable-uoa --enable-vala-bindings
build      : |
    %make
install    : |
    %make_install
    
