name       : evolution-data-server
version    : 3.28.3
release    : 37
source     :
    - https://download.gnome.org/sources/evolution-data-server/3.28/evolution-data-server-3.28.3.tar.xz : 437e91f03fe49bf531416d30828e943aa2c74d657aeb44fb637997104a3a5887
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - gperf
    - openldap-devel
    - vala
setup      : |
    %cmake \
        -DENABLE_INTROSPECTION=ON \
        -DENABLE_UOA=OFF \
        -DENABLE_VALA_BINDINGS=ON \
        -DWITH_KRB5=OFF .
build      : |
    %make
install    : |
    %make_install

