name       : evolution-data-server
version    : 3.46.2
release    : 79
source     :
    - https://download.gnome.org/sources/evolution-data-server/3.46/evolution-data-server-3.46.2.tar.xz : f9bd52008b7e535d816920cfcec70a0e5562bde28af71f996e203ff6a86e46e0
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(gweather4)
    - pkgconfig(icu-uc)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.1)
    - pkgconfig(webkit2gtk-5.0)
    - db5-devel
    - gperf
    - openldap-devel
    - vala
setup      : |
    %cmake \
        -DENABLE_INTROSPECTION=ON \
        -DENABLE_UOA=OFF \
        -DENABLE_VALA_BINDINGS=ON \
        -DSYSCONF_INSTALL_DIR="/usr/share" \
        -DWITH_KRB5=OFF \
        -DENABLE_GTK4=ON \
        -DENABLE_WEATHER=ON .
build      : |
    make -j1
install    : |
    %make_install

