name       : evolution-data-server
version    : 3.16.1
release    : 2
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/evolution-data-server/3.16/evolution-data-server-3.16.1.tar.xz : 04eedf170708c97ca807951f47e6d6f554bee94c35bc279201a54f64b744eb51
clang      : no
license    : GPL-2.0
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(icu-uc)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(sqlite3)
    - pkgconfig(libgdata)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - gperf
setup      : |
    %configure --disable-static --disable-uoa
build      : |
    %make
install    : |
    %make_install
    
