name       : evolution-data-server
version    : 3.18.3
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evolution-data-server/3.18/evolution-data-server-3.18.3.tar.xz : 9de9d6392822bb4b89318a88f5db1fd2f0f09899b793a0dd5525a656ed0e8163
license    : GPL-2.0
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(icu-uc)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(sqlite3)
    - pkgconfig(libgdata)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - gperf
    - vala
setup      : |
    %configure --disable-static --disable-uoa --enable-vala-bindings
build      : |
    %make
install    : |
    %make_install
    
