name       : evolution-data-server
version    : 3.26.2
release    : 26
source     :
    - https://download.gnome.org/sources/evolution-data-server/3.26/evolution-data-server-3.26.2.tar.xz : 0a327b8079f05ad258e63c4483bde46a181a50ab46e9faf13a51e117c40f9152
license    : GPL-2.0
component  : desktop.gnome.core
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - gperf
    - openldap-devel
    - vala
setup      : |
    %cmake \
        -DENABLE_INTROSPECTION=ON \
        -DENABLE_UOA=OFF \
        -DENABLE_VALA_BINDINGS=ON \
        -DWITH_KRB5=OFF .
build      : |
    %make
install    : |
    %make_install

