name       : evolution-data-server
version    : 3.20.4
release    : 13
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evolution-data-server/3.20/evolution-data-server-3.20.4.tar.xz : f250e3ccb8b6308086f330a1766b235a9d2643ae3e170384eb6391316d0b080e
license    : GPL-2.0
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(icu-uc)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(sqlite3)
    - pkgconfig(libgdata)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(webkitgtk-3.0)
    - gperf
    - vala
    - pkgconfig(gobject-introspection-1.0)
setup      : |
    %configure --disable-static --disable-uoa --enable-vala-bindings
build      : |
    %make
install    : |
    %make_install

