name       : evolution-data-server
version    : 3.18.5
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evolution-data-server/3.18/evolution-data-server-3.18.5.tar.xz : a897c789925e86df31a1c78212b431cca13dc4d5a3d87e1fb3d507df3994e8e1
license    : GPL-2.0
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(icu-uc)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(sqlite3)
    - pkgconfig(libgdata)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - gperf
    - vala
    - pkgconfig(gobject-introspection-1.0)
setup      : |
    %configure --disable-static --disable-uoa --enable-vala-bindings
build      : |
    %make
install    : |
    %make_install
    
