name       : evolution-data-server
version    : 3.24.5
release    : 23
source     :
    - https://download.gnome.org/sources/evolution-data-server/3.24/evolution-data-server-3.24.5.tar.xz : 6d8ec04b79c02bb517cc3e23ac3b23c7503465dfa27b7415955201a2f62844e1
license    : GPL-2.0
component  : desktop.gnome.core
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - gperf
    - vala
setup      : |
    %cmake \
        -DENABLE_INTROSPECTION=ON \
        -DENABLE_UOA=OFF \
        -DENABLE_VALA_BINDINGS=ON \
        -DWITH_KRB5=OFF \
        -DWITH_OPENLDAP=OFF .
build      : |
    %make
install    : |
    %make_install

