name       : evolution-data-server
version    : 3.24.0
release    : 20
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/evolution-data-server/3.24/evolution-data-server-3.24.0.tar.xz : 41ddb60b08ee287e82be52ebbe49b5a336984e52584a5fd34c82d45493f8031b
license    : GPL-2.0
component  : desktop.gnome.core
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libgdata)
    - pkgconfig(libical)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - gperf
    - vala
setup      : |
    %cmake \
        -DENABLE_INTROSPECTION=ON \
        -DENABLE_UOA=OFF \
        -DENABLE_VALA_BINDINGS=ON \
        -DWITH_KRB5=OFF \
        -DWITH_OPENLDAP=OFF .
build      : |
    %make
install    : |
    %make_install

