name       : evolution-data-server
version    : 3.18.1
release    : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evolution-data-server/3.18/evolution-data-server-3.18.1.tar.xz : 4fe7c520a49d4c7fd67ed6fc2dfb33667f6138368c7bbe3ecd8c4ad2356771bc
clang      : no
license    : GPL-2.0
summary    : Centralized access to appointments and contacts
description: |
    Centralized access to appointments and contacts
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(nspr)
    - pkgconfig(nss)
    - pkgconfig(icu-uc)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(sqlite3)
    - pkgconfig(libgdata)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - gperf
    - vala
setup      : |
    %configure --disable-static --disable-uoa   --enable-vala-bindings
build      : |
    %make
install    : |
    %make_install
    
